### ISSUE TITLE
Is Melon Mail compatible with the existing traditional e-mail protocol?

### ISSUE THREAD

**Issue by ferittuncer** [melonproject/melon-mail#5]
I wonder if anyone can send me an e-mail from a Gmail (or whatever) account?

**Comment by Matko95** [comment]
Although it's not compatible, you could easily make a bridge that works with existing mail systems but you would lose on the decentralization and would have to figure out a way to handle the decryption of the mails.

**Comment by ferittuncer** [comment]
Thank you for answering. I think it would be awesome if we could bridge this with the  traditional protocol because it would accelerate adoption, I think.
